from typing import Optional, Protocol
from uuid import UUID

from .entities import User, UserStatistic


class UserRepository(Protocol):
    async def get_by_id(self, user_id: UUID) -> Optional[User]: ...

    async def get_by_username(self, username: str) -> Optional[User]: ...

    async def get_by_email(self, email: str) -> Optional[User]: ...

    async def get_all(self, skip: int = 0, limit: int = 100) -> list[User]: ...

    async def search_by_username(self, query: str, skip: int = 0, limit: int = 100) -> list[User]: ...

    async def create(self, user: User) -> User: ...

    async def update(self, user: User) -> User: ...

    async def delete(self, user_id: UUID) -> bool: ...


class UnitOfWork(Protocol):
    async def commit(self) -> None: ...

    async def rollback(self) -> None: ...


class StatisticRepository(Protocol):
    async def get_by_user_id(self, user_id: UUID) -> Optional[UserStatistic]: ...

    async def create(self, user_id: UUID) -> UserStatistic: ...

    async def increment_field(self, user_id: UUID, field: str, amount: int = 1) -> None: ...

    async def decrement_field(self, user_id: UUID, field: str, amount: int = 1) -> None: ...
