# domain/interfaces/video_repository.py
from typing import Protocol
from uuid import UUID
from src.domain.entities.video import Video, VideoStatus

class VideoRepositoryProtocol(Protocol):
    async def add(self, video: Video) -> None: ...
    async def get(self, video_id: UUID) -> Video | None: ...
    async def list(self, limit: int, offset: int, user_id: UUID | None = None) -> list[Video]: ...
    async def count(self, user_id: UUID | None = None) -> int: ...
    async def update(self, video: Video) -> None: ...
    async def update_status(self, video_id: UUID, status: VideoStatus) -> None: ...
    async def delete(self, video_id: UUID) -> None: ...